"""your message

Revision ID: 6ef27c7a6eb6
Revises: f3dee8f14e4f
Create Date: 2025-06-15 18:00:58.271278

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ef27c7a6eb6'
down_revision = 'f3dee8f14e4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
